# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f707711ba1aaee44caf1e722d1160bbbe8d847c21a02bea3acfb6f560cdb5481bac808d17ed1c906902e4a21a84ecc5d925fdd693e7771e8dd4f4012580609c1

test:
  secret_key_base: c777f43189997fb3a3a3e36671a3bbe4bc14bc1850b28a37eeb708527932593fd26cf293ae476a4dd02a95205459b986a88a1928b11f3e382ce0c5abb087de1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
